Repository cognovi-ai/the-cdj, pull requests merged in 2024-09, with the labels that each got.

#160 Let Express set port for test environment.
  backend/package-lock.json
  backend/src/index.ts
  backend/tests/index.test.ts
  backend/tests/jest.setup.cjs
  backend/tests/jest.teardown.cjs
Labels: major, refactor, api

#158 139 Utils Migration
  backend/data/seed.js
  backend/package-lock.json
  backend/src/index.ts
  backend/src/utils/ExpressError.ts
  backend/src/utils/aes.ts
  backend/src/utils/catchAsync.js
  backend/src/utils/catchAsync.ts
  backend/tests/index.test.ts
  backend/tests/jest.setup.cjs
  backend/tests/jest.teardown.cjs
  backend/tests/utils/ExpressError.test.ts
  backend/tests/utils/aes.test.ts
  backend/tests/utils/catchAsync.test.ts
Labels: major, refactor, test, api

#159 Migrate db.js to TS with unit tests.
  backend/package.json
  backend/src/db.ts
  backend/tests/db.test.ts
  backend/tsconfig.json
  backend/tsconfig.test.json
Labels: major, refactor, api

#161 139 Migrate app.js and store.js to TS with unit tests.
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/store.js
  backend/src/store.ts
  backend/src/types/express/index.d.ts
  backend/tests/app.test.ts
  backend/tests/store.test.ts
Labels: bug, major, refactor, api

#163 refactor!: migrate assistants to TS with unit tests
  backend/src/assistants/Assistant.js
  backend/src/assistants/Assistant.ts
  backend/src/assistants/gpts/CdGpt.ts
  backend/tests/assistants/Assistant.test.js
  backend/tests/assistants/Assistants.test.ts
  backend/tests/assistants/gpts/CdGpt.test.js
  backend/tests/assistants/gpts/CdGpt.test.ts
Labels: enhancement, major, refactor, ai
