Repository cognovi-ai/the-cdj, pull requests merged in 2024-11, with the labels that each got.

#183 refactor!: migrate controllers to TS
  backend/jest.config.cjs
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/assistants/gpts/CdGpt.ts
  backend/src/controllers/access/access.ts
  backend/src/controllers/entry/entry.ts
  backend/src/controllers/index.ts
  backend/src/models/entry/entryAnalysis.ts
  backend/src/models/entry/entryConversation.ts
  backend/src/models/user.ts
  backend/tests/assistants/gpts/CdGpt.test.ts
Labels: major, refactor, api

#187 refactor: create service layer for read operations
  backend/src/controllers/entry/entry.ts
  backend/src/models/services/entry/entry.ts
  backend/tests/models/services/entry/entry.test.ts
Labels: refactor, test

#185 refactor!: migrate access middleware to TS with unit tests
  backend/package-lock.json
  backend/package.json
  backend/src/middleware/access.js
  backend/src/middleware/access.ts
  backend/tests/middleware/access.test.ts
Labels: major, refactor, api

#193 refactor!: migrate validation middleware to TS with unit tests
  backend/src/middleware/validation.js
  backend/src/middleware/validation.ts
  backend/tests/middleware/validation.test.ts
Labels: major, refactor, api, middleware

#195 refactor!: create service layers for create, update, and delete operations
  backend/src/controllers/entry/entry.ts
  backend/src/models/services/entry/entry.ts
  backend/tests/jest.setup.cjs
  backend/tests/jest.teardown.cjs
  backend/tests/models/services/entry/entry.test.ts
Labels: refactor, test

#208 chore: add test env vars
  .github/workflows/node.js.yml
Labels: patch, ci

#209 fix: allow multi-line secret
  .github/workflows/node.js.yml
Labels: patch, ci
